package com.mralmost.community.model;

public class GithubUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.account_id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.username
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.token
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.create_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.modified_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.sign
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_user.avatar
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.id
     *
     * @return the value of github_user.id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.id
     *
     * @param id the value for github_user.id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.account_id
     *
     * @return the value of github_user.account_id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.account_id
     *
     * @param accountId the value for github_user.account_id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.username
     *
     * @return the value of github_user.username
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.username
     *
     * @param username the value for github_user.username
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.token
     *
     * @return the value of github_user.token
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.token
     *
     * @param token the value for github_user.token
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.create_time
     *
     * @return the value of github_user.create_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.create_time
     *
     * @param createTime the value for github_user.create_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.modified_time
     *
     * @return the value of github_user.modified_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.modified_time
     *
     * @param modifiedTime the value for github_user.modified_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setModifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime == null ? null : modifiedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.sign
     *
     * @return the value of github_user.sign
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.sign
     *
     * @param sign the value for github_user.sign
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_user.avatar
     *
     * @return the value of github_user.avatar
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_user.avatar
     *
     * @param avatar the value for github_user.avatar
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}