package com.mralmost.community.model;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.user_id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.question_id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_date
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    private Date recordDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.user_id
     *
     * @return the value of record.user_id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.user_id
     *
     * @param userId the value for record.user_id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.question_id
     *
     * @return the value of record.question_id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.question_id
     *
     * @param questionId the value for record.question_id
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_date
     *
     * @return the value of record.record_date
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_date
     *
     * @param recordDate the value for record.record_date
     *
     * @mbg.generated Wed Feb 05 20:49:28 CST 2020
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
}