package com.mralmost.community.model;

public class RegisterUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.username
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.password
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.avatar
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.create_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.last_date
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String lastDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.sign
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.code
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_user.email
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.id
     *
     * @return the value of register_user.id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.id
     *
     * @param id the value for register_user.id
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.username
     *
     * @return the value of register_user.username
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.username
     *
     * @param username the value for register_user.username
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.password
     *
     * @return the value of register_user.password
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.password
     *
     * @param password the value for register_user.password
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.avatar
     *
     * @return the value of register_user.avatar
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.avatar
     *
     * @param avatar the value for register_user.avatar
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.create_time
     *
     * @return the value of register_user.create_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.create_time
     *
     * @param createTime the value for register_user.create_time
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.last_date
     *
     * @return the value of register_user.last_date
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.last_date
     *
     * @param lastDate the value for register_user.last_date
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setLastDate(String lastDate) {
        this.lastDate = lastDate == null ? null : lastDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.sign
     *
     * @return the value of register_user.sign
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.sign
     *
     * @param sign the value for register_user.sign
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.code
     *
     * @return the value of register_user.code
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.code
     *
     * @param code the value for register_user.code
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_user.email
     *
     * @return the value of register_user.email
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_user.email
     *
     * @param email the value for register_user.email
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}