package com.mralmost.community.mapper;

import com.mralmost.community.model.RegisterUser;
import com.mralmost.community.model.RegisterUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegisterUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    long countByExample(RegisterUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int deleteByExample(RegisterUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int insert(RegisterUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int insertSelective(RegisterUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    List<RegisterUser> selectByExample(RegisterUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    RegisterUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") RegisterUser record, @Param("example") RegisterUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int updateByExample(@Param("record") RegisterUser record, @Param("example") RegisterUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int updateByPrimaryKeySelective(RegisterUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_user
     *
     * @mbg.generated Wed Mar 04 21:53:55 CST 2020
     */
    int updateByPrimaryKey(RegisterUser record);
}